services:

  db:
    image: napstr/poggres:18
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres-data/:/var/lib/postgresql/
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      # See https://github.com/napstr/poggres#env-vars
      - ROLE=wolfia
      - PASSWORD=${DB_PASS}
      - DB=wolfia
      - EXTENSIONS=hstore
      - BACKUP_DB=wolfia
      - BACKUP_APPNAME=wolfia
      - BACKUP_PASS=${BACKUP_ENCRYPTION_PASS}
      - BACKUP_BUCKET_DAILY=wolfia-backups-daily
      - BACKUP_BUCKET_WEEKLY=wolfia-backups-weekly
      - BACKUP_BUCKET_MONTHLY=wolfia-backups-monthly
      - BACKUP_ACCOUNT_ID=${B2_ACCOUNT_ID}
      - BACKUP_APP_KEY=${B2_APP_KEY}

  redis:
    image: redis:8.2
    restart: always
    entrypoint:
      - redis-server
      - --appendonly
      - "yes"
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./redis-data:/data
    sysctls:
      - net.core.somaxconn=511   # container was spitting out a warning telling us to do this

  redis-exporter:
    image: oliver006/redis_exporter
    restart: always
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=9121"
      - "traefik.http.routers.wolfia-redis-exporter-prom.rule=Host(`redis.${DOMAIN}`) && PathPrefix(`/metrics`)"
      - "traefik.http.routers.wolfia-redis-exporter-prom.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wolfia-redis-exporter-prom.middlewares=metrics-auth@docker, whitelist@docker"

  bot:
    image: napstr/wolfia:master
    restart: always
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=4567"
      # metrics
      - "traefik.http.routers.wolfia-metrics.rule=Host(`bot.${DOMAIN}`) && PathPrefix(`/metrics`)"
      - "traefik.http.routers.wolfia-metrics.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wolfia-metrics.middlewares=metrics-auth@docker, whitelist@docker"
      # ideas redirect
      - "traefik.http.middlewares.wolfia-ideas-redirect.redirectregex.regex=^https?://bot\\.${DOMAIN}/ideas.*"
      - "traefik.http.middlewares.wolfia-ideas-redirect.redirectregex.replacement=https://feedback.userreport.com/01987d31-0d58-48c6-a4d3-96f2ae42eb14"
      - "traefik.http.middlewares.wolfia-ideas-redirect.redirectregex.permanent=false"
      # join redirect
      - "traefik.http.middlewares.wolfia-join-redirect.redirectregex.regex=^https?://bot\\.${DOMAIN}/join.*"
      - "traefik.http.middlewares.wolfia-join-redirect.redirectregex.replacement=https://discord.gg/nvcfX3q"
      - "traefik.http.middlewares.wolfia-join-redirect.redirectregex.permanent=false"
      # bot
      - "traefik.http.routers.wolfia-bot.rule=Host(`bot.${DOMAIN}`)"
      - "traefik.http.routers.wolfia-bot.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wolfia-bot.middlewares=whitelist@docker, wolfia-ideas-redirect@docker, wolfia-join-redirect@docker"
    ports:
      - 127.0.0.1:4567:4567   # Wolfia web server
      - 127.0.0.1:5005:5005   # Remote debug
    volumes:
      - ./wolfia-secrets.yaml:/opt/wolfia/wolfia-secrets.yaml:ro
      - ./logs:/opt/wolfia/logs
      - ./logs/gc:/opt/wolfia/logs/gc
    stop_grace_period: 7200s #should really be enough to finish all games
    entrypoint:
      - java
      - -Xms12g
      - -Xmx12g
      - -XX:+AlwaysPreTouch
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=emergencydump.hprof
      - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - -XX:+EnableDynamicAgentLoading
      - -Xlog:gc*:logs/gc/gc-%t.log::filesize=1g
      - -XX:+UseZGC
      - -XX:+UseTransparentHugePages
      - -XX:+UseStringDeduplication
      - -jar
      - wolfia.jar
